EstaAllCompany_CMS/Infrastructure/Components/MainMenuViewComponent.cs
using EstaAllCompany_CMS.Infrastructure.Context;
using EstaAllCompany_CMS.Infrastructure.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EstaAllCompany_CMS.Infrastructure.Components
{
    public class MainMenuViewComponent : ViewComponent //ViewComponent'dan miras alır.
    {
        private readonly ProjectContext _context;
        public MainMenuViewComponent(ProjectContext context)
        {
            this._context = context;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var pages = await GetPageAsync();//aşagıdaki işleride yani Task'ları bana burası çağırır birbirlerini beklemeden asenkron olarak çalısacak aşagıdaki belirteceğim bütün Task'ları çağırabilirim.Biz bu işlmide Delegatlerle yapıyoruz.
            return View(pages);
        }
        //Delegate:Bir yada birden fazla Taskı(yani işi) yönetmek için kullandığım bir yapıdır.Birde bunları Asenkron olarak tasarlarsam birbirini beklemeden işlemler gerçekleşir.

        private Task<List<Page>> GetPageAsync()//birden fazle sayfa olacağından Liste tipine aldık page'leri 
        {
            return _context.Pages.OrderBy(x => x.Sorting).ToListAsync();//Bize Page'leri sorting yani home=0'dı 0'dan başlayarak 1,2,3... diye sıralayıp bana getirecek.
        }
    }
}

EstaAllCompany_CMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EstaAllCompany</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-info border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EstaAllCompany</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @await Component.InvokeAsync("MainMenu") 
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_NotificationPartial" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - EstaAllCompany- <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

EstaAllCompany_CMS/Views/Shared/_NotificationPartial.cshtml
@if (TempData["Success"] != null)
{
    <div class="alert alert-success notification">
        @TempData["Success"]
    </div>
}


@if (TempData["Error"] != null)
{
    <div class="alert alert-danger notification">
        @TempData["Error"]
    </div>
}


@if (TempData["Success"] != null)
{
    <div class="alert alert-warning notification">
        @TempData["Warning"]
    </div>
}